# Application Properties
spring:
  application:
    name: Exemplo Spring Liquibase
  # Jpa Properties
  datasource:
    url: jdbc:postgresql://localhost:5432/springliquibasedb?serverTimezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  # Liquibase properties
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-dev.xml

## Server Properties
server:
  port: 8081
