# Application Properties
spring:
  application:
    name: Exemplo Spring Liquibase
  # Jpa Properties
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none

  # Liquibase properties
  liquibase:
    enabled: false

## Server Properties
server:
  port: 8081
